import { Skill } from './types';

export const skills: Skill[] = [
  // STRONG EVIDENCE
  { name: 'TypeScript', tier: 'strong', category: 'language',
    evidenceRepos: [{ label: 'ai-chat-manager', url: 'https://github.com/RiasGremoryHSDXD/ai-chat-manager' }] },
  { name: 'JavaScript', tier: 'strong', category: 'language',
    evidenceRepos: [{ label: 'Vibeo', url: 'https://github.com/RiasGremoryHSDXD/Vibeo' }] },
  { name: 'React', tier: 'strong', category: 'frontend',
    evidenceRepos: [{ label: 'ai-chat-manager', url: 'https://github.com/RiasGremoryHSDXD/ai-chat-manager' }] },
  { name: 'React Native', tier: 'strong', category: 'mobile',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'HTML', tier: 'strong', category: 'frontend',
    evidenceRepos: [{ label: 'StudentForecasting-Frontend', url: 'https://github.com/RiasGremoryHSDXD/StudentForecasting-Frontend' }] },
  { name: 'CSS', tier: 'strong', category: 'frontend',
    evidenceRepos: [{ label: 'WebsitePortfolio', url: 'https://github.com/RiasGremoryHSDXD/WebsitePortfolio' }] },
  { name: 'Tailwind CSS', tier: 'strong', category: 'frontend',
    evidenceRepos: [{ label: 'WebsitePortfolio', url: 'https://github.com/RiasGremoryHSDXD/WebsitePortfolio' }] },
  { name: 'Python', tier: 'strong', category: 'backend',
    evidenceRepos: [{ label: 'Serbisure-backend', url: 'https://github.com/RiasGremoryHSDXD/Serbisure-backend' }] },
  { name: 'Express.js', tier: 'strong', category: 'backend',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Django', tier: 'strong', category: 'backend',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'FastAPI', tier: 'strong', category: 'backend',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'MongoDB', tier: 'strong', category: 'database',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'PostgreSQL', tier: 'strong', category: 'database',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Supabase', tier: 'strong', category: 'platform',
    evidenceRepos: [{ label: 'WebsitePortfolio', url: 'https://github.com/RiasGremoryHSDXD/WebsitePortfolio' }] },
  { name: 'Firebase', tier: 'strong', category: 'platform',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Neon', tier: 'strong', category: 'database',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Cloudinary', tier: 'strong', category: 'platform',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Docker', tier: 'strong', category: 'devops',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Vercel', tier: 'strong', category: 'devops',
    evidenceRepos: [{ label: 'Confirmed by James', url: '#' }] },
  { name: 'Git / GitHub', tier: 'strong', category: 'tool',
    evidenceRepos: [{ label: 'RiasGremoryHSDXD', url: 'https://github.com/RiasGremoryHSDXD' }] },
  { name: 'ML Integration', tier: 'strong', category: 'ai-ml',
    evidenceRepos: [{ label: 'Vibeo', url: 'https://github.com/RiasGremoryHSDXD/Vibeo' }] },

  // ACADEMIC / PRACTICE EVIDENCE
  { name: 'Java', tier: 'academic', category: 'language',
    evidenceRepos: [{ label: 'LibraryManagementSystem', url: 'https://github.com/RiasGremoryHSDXD/LibraryManagementSystem' }] },
  { name: 'PHP', tier: 'academic', category: 'language',
    evidenceRepos: [{ label: 'Student-Management-System', url: 'https://github.com/RiasGremoryHSDXD/Student-Management-System' }] },
  { name: 'C', tier: 'academic', category: 'language',
    evidenceRepos: [{ label: 'Automated-GradeManagementSystem', url: 'https://github.com/RiasGremoryHSDXD/Automated-GradeManagementSystem' }] },
  { name: 'MySQL', tier: 'academic', category: 'database',
    evidenceRepos: [{ label: 'LibraryManagementSystem', url: 'https://github.com/RiasGremoryHSDXD/LibraryManagementSystem' }] },
  { name: 'Astro', tier: 'academic', category: 'frontend',
    evidenceRepos: [{ label: 'SITE-USTP-Website', url: 'https://github.com/RiasGremoryHSDXD/SITE-USTP-Website' }] },
  { name: 'IntelliJ IDEA', tier: 'academic', category: 'tool',
    evidenceRepos: [{ label: 'Asset present', url: '#' }] },
  { name: 'PyCharm', tier: 'academic', category: 'tool',
    evidenceRepos: [{ label: 'Asset present', url: '#' }] },
];
